### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Haohaoscreamandrun**
感謝!
http://13.236.21.10:8000/
http://127.0.0.1:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Details: line, spacing, and padding.
13 236 21 10_8000_attraction_2

**Comment by Haohaoscreamandrun** [comment]
http://13.236.21.10:8000/
http://13.236.21.10:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Separating line of navigation bar should extend to full width on desktop layout.
- Add link to homepage on website title

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
