### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Haohaoscreamandrun**
陳昊
http://140.112.3.5:8000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot connect to your website.

**Comment by Haohaoscreamandrun** [comment]
Sorry, wrong address!
http://13.236.21.10:8000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
- We should show order number on the thankyou page.
- I cannot back to booking page after ordering for the next order.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
