### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Haohaoscreamandrun**
http://13.236.21.10:8000/
http://13.236.21.10:8000/attraction/10
http://13.236.21.10:8000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Response of Booking APIs should be JSON format, not a string.
- First separating line in the booking page should extend to the full width.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by cwpeng** [comment]
You should merge pull request after review approval.

**Comment by Haohaoscreamandrun** [comment]
Sorry ! Let me merge it right now.

Chao-Wei Peng ***@***.***> 於 2024年7月1日 週一 17:36 寫道：

**Pull request merged**
